2021-10-26 17:08:42,292 Downloading and reading train artifact
wandb: ERROR Project default141/exercise_14 does not contain artifact: "processed_segregated_data.csv:latest"
Traceback (most recent call last):
  File "/home/default/miniconda3/envs/mlflow-259d53ab44a1e9011b0c64ae862f43343c0fc9e5/lib/python3.8/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/home/default/miniconda3/envs/mlflow-259d53ab44a1e9011b0c64ae862f43343c0fc9e5/lib/python3.8/site-packages/wandb/apis/public.py", line 520, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
  File "/home/default/miniconda3/envs/mlflow-259d53ab44a1e9011b0c64ae862f43343c0fc9e5/lib/python3.8/site-packages/wandb/apis/public.py", line 2583, in __init__
    self._load()
  File "/home/default/miniconda3/envs/mlflow-259d53ab44a1e9011b0c64ae862f43343c0fc9e5/lib/python3.8/site-packages/wandb/apis/public.py", line 3097, in _load
    raise ValueError(
ValueError: Project default141/exercise_14 does not contain artifact: "processed_segregated_data.csv:latest"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 263, in <module>
    go(args)
  File "run.py", line 33, in go
    train_data_path = run.use_artifact(args.train_data).file()
  File "/home/default/miniconda3/envs/mlflow-259d53ab44a1e9011b0c64ae862f43343c0fc9e5/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1957, in use_artifact
    artifact = public_api.artifact(type=type, name=name)
  File "/home/default/miniconda3/envs/mlflow-259d53ab44a1e9011b0c64ae862f43343c0fc9e5/lib/python3.8/site-packages/wandb/apis/normalize.py", line 62, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "/home/default/miniconda3/envs/mlflow-259d53ab44a1e9011b0c64ae862f43343c0fc9e5/lib/python3.8/site-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/home/default/miniconda3/envs/mlflow-259d53ab44a1e9011b0c64ae862f43343c0fc9e5/lib/python3.8/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/home/default/miniconda3/envs/mlflow-259d53ab44a1e9011b0c64ae862f43343c0fc9e5/lib/python3.8/site-packages/wandb/apis/public.py", line 520, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
  File "/home/default/miniconda3/envs/mlflow-259d53ab44a1e9011b0c64ae862f43343c0fc9e5/lib/python3.8/site-packages/wandb/apis/public.py", line 2583, in __init__
    self._load()
  File "/home/default/miniconda3/envs/mlflow-259d53ab44a1e9011b0c64ae862f43343c0fc9e5/lib/python3.8/site-packages/wandb/apis/public.py", line 3097, in _load
    raise ValueError(
wandb.errors.error.CommError: Project default141/exercise_14 does not contain artifact: "processed_segregated_data.csv:latest"
